# -*- coding: utf-8 -*-
"""Project6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M3cIUrbx8aCaH7BsNJ_o7298WRbZJDA
"""

# Project 6: Countdown Timer Python Project

import time

def countdown(seconds):
    while seconds:
        minute = seconds // 60
        second = seconds % 60
        if second < 10 and minute < 10:
            minute = f"0{minute}"
            second = f"0{second}"
            print(f"{minute}:{second}")
        else:
            print(f"0{minute}:{second}")
        time.sleep(1)
        seconds = seconds - 1
    print("The timer has completed!")


num : int = int(input("Enter the time in seconds: "))
countdown(num)