# -*- coding: utf-8 -*-
"""Project7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHht29cXqFTJFUKJOQUgA9qJKVpe_dJV
"""

# Project 7: Password Generator Python Project

import string
import random

''' The password is a maximum length of 12 and a minimum of 8. Password contains
    alphabets, digits and special characters.'''


while True:
  length : int = int(input("Enter password length (max length : 12 & min length : 8): "))
  if length > 12 or length < 8:
	  raise ValueError("Password length should between 8 & 12")
  else:
    str1 : str = ""
    str1 = ''.join(random.choices(string.ascii_letters + string.digits + string.punctuation, k=length))
    print(f"The password is {str1}\n")
    ask : str = input("Are you want a new password? Enter yes/no : ")
    if ask.lower() == "yes":
      continue
    else:
      break