# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cceu0rZKfN8BkmZMD69unyInmccAIZGR
"""

#  Project 2: Guess the Number Game Python Project (Computer)

import random
import time

num : int = int(input("Enter a number between 1 to 10 : "))

print("Computer have three number of chances to guess the correct number entered by you.")

for i in range(4):
  time.sleep(5)
  if(i>2):
    print(f"Game Over! Your number was {num}. The computer guess chances ended!")
    break

  else:
    Guess_num : int = random.randint(1, 10)
    print(f"Computer guess number is : {Guess_num}")

    if (Guess_num == num):
      print("Congrants! Computer win the number guessing game.")
      break

    elif (Guess_num > num):
      print("Computer guess the heigher number.")

    elif (Guess_num < num):
      print("Computer guess the lower number.")