# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1goqkijaYi6aEM3YYn8nvYNzz3pcVEY
"""

# Project 1: Mad libs Python Project

def madlib_first(color, name, verb, adjective, food):
    story = f"It was {color}-day at school, and {name} was super {adjective} for lunch. But when {name} went outside to eat, a bird stole her {food}! {name} chased the bird all over school. Luckily, {name}’s friends were willing to share their {food} with {name}."
    print(story)




color : str = input("Enter the name of color : ")
name : str = input("Enter the name of the student : ")
verb : str = input("Enter the verb : ")
adjective : str = input("Enter the adjective : ")
food : str = input("Enter the name of the food : ")

if (color.isalpha() and name.isalpha() and verb.isalpha() and adjective.isalpha() and food.isalpha()):
  madlib_first(color, name, verb, adjective, food)

else:
   raise ValueError("The value is not a string.")