# -*- coding: utf-8 -*-
"""Project3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFV0-WevxAL7hQ5ejgm9zMkNopSj0EsI
"""

#  Project 3: Guess the Number Game Python Project (User)


import random


num : int = random.randint(1, 10)

print("You have three number of chances to guess the correct number.")

for i in range(4):

  if(i>2):
    print(f"Game Over! The number was {num}. The guess chances ended!")
    break
  else:
    Guess_num : int = int(input("Enter a guessing number between 1 to 10 : "))
    if (Guess_num == num):
      print("Congrants! You win the number guessing game.")
      break

    elif (Guess_num > num):
      print("You guess the heigher number.")

    elif (Guess_num < num):
      print("You guess the lower number.")