# -*- coding: utf-8 -*-
"""project9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_iBFzo1_iggJuszvLgm9hYdrW1kFNOp
"""

# Project 9: Build a Python Website in 15 Minutes With Streamlit

# Create a file of this colab code, name file with project9.py and upload the file in colab, then run following commands in colab

# !pip install streamlit
# !pip install pyngrok
# !npm install -g localtunnel
# !wget -q -O - ipv4.icanhazip.com
# !streamlit run project9.py & npx localtunnel --port 8501


import streamlit as st

st.title("My PIAIC Quarter1 Projects")

option = st.selectbox("Options", ['', 'Project-1', 'Project-2', 'Project-3', 'Project-4', 'Project-5', 'Project-6', 'Project-6', 'Project-7', 'Project-8'])
st.write('You selected:', option)
st.write(f"Following is the Colab link of {option}.\n")

if option == "Project-1":
  st.info("https://colab.research.google.com/drive/1E1goqkijaYi6aEM3YYn8nvYNzz3pcVEY?usp=sharing")
elif option == "Project-2":
  st.info("https://colab.research.google.com/drive/1cceu0rZKfN8BkmZMD69unyInmccAIZGR?usp=sharing")
elif option == "Project-3":
  st.info("https://colab.research.google.com/drive/1KFV0-WevxAL7hQ5ejgm9zMkNopSj0EsI?usp=sharing")
elif option == "Project-4":
  st.info("https://colab.research.google.com/drive/1iEYGKrtyQQi75IiAU9WvgwL46zOkbwGA?usp=sharing")
elif option == "Project-5":
  st.info("https://colab.research.google.com/drive/1pWhKnKX-hMIaxvXAnIIlyAUxQ1nnoIir?usp=sharing")
elif option == "Project-6":
  st.info("https://colab.research.google.com/drive/19M3cIUrbx8aCaH7BsNJ_o7298WRbZJDA?usp=sharing")
elif option == "Project-7":
  st.info("https://colab.research.google.com/drive/1xHht29cXqFTJFUKJOQUgA9qJKVpe_dJV?usp=sharing")
elif option == "Project-8":
  st.info("https://colab.research.google.com/drive/1OT1cd4zMTVI3tuiViyD3N2lyzWAmkIat?usp=sharing")