# -*- coding: utf-8 -*-
"""project8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OT1cd4zMTVI3tuiViyD3N2lyzWAmkIat
"""

# Project 8: Create a Python Streamlit BMI Calculator Web App in Just 6 Minutes

# This is the link used to get bmi calculations https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmicalc.htm
# Create a file of this colab code, name file with project8.py and upload the file in colab, then run following commands in colab

# !pip install streamlit
# !pip install pyngrok
# !npm install -g localtunnel
# !wget -q -O - ipv4.icanhazip.com
# !streamlit run project8.py & npx localtunnel --port 8501

import streamlit as st

st.title('BMI Calculator Web App')

weight = st.number_input("Enter your weight in kg")
h1 = st.number_input("Enter your height in foot")
h2 = st.number_input("Enter your remaining height in inches")
h1 = h1*0.3048
h2 = h2*0.0254
height = h1+h2

if(st.button('Check BMI')) :
  bmi = weight / (height ** 2)

  st.write(f"Your BMI index is {bmi}.")

  if(bmi < 18.5):
    st.warning("You are Underweight!")
  elif(bmi >= 18.5 and bmi < 24.9):
    st.success("You have normal weight!")
  elif(bmi >= 25 and bmi <= 29.9):
    st.warning("You are Overweight!")
  elif(bmi > 30):
    st.error("Obesity (having too much body fat relative to height)!")